version: "3.8"

services:
  ytuner:
    image: ghcr.io/tobiaspankner/ytuner:latest
    container_name: ytuner
    network_mode: host
    volumes:
      - ./data:/app/host-shared
    restart: unless-stopped
